import express from 'express';
import authRouter from './authRoutes.js';
import productRouter from './productRoutes.js';
import productReviewRoutes from './productReviewRoutes.js';
import shopDetail from './shopDetailRoutes.js';
import cloudinaryRouter from './cloudinaryRouter.js';
import userRouter from './userRoutes.js';
import chatRouter from './chatRoutes.js';
import UnitProductRoutes from './unitProductRoutes.js';
import orderRoutes from './orderRoutes.js';
import kycRoutes from './kycRoutes.js';
import adminRoutes from './adminRoutes.js';
import userManagementRoutes from './userManagementRoutes.js';
import orderManagementRoutes from './orderManagementRoutes.js';

import categoryRouter from './categoryRoutes.js';
import orderEvidenceRoutes from './orderEvidenceRoutes.js';
import depositRoutes from './depositRoutes.js';
import depositPolicyRoutes from './depositPolicyRoutes.js';
import { chatController } from '../controllers/aiController.js';
const router = express.Router();

router.use('/auth', authRouter);
router.use('/product', productRouter);
router.use('/products', productRouter);
router.use('/category', categoryRouter);
router.use('/productReview', productReviewRoutes);
router.use('/shopDetail', shopDetail);
router.use('/cloudinary', cloudinaryRouter);
router.use('/users', userRouter);
router.use('/chatrooms', chatRouter);
router.use('/order-products', UnitProductRoutes);
router.use('/order-evidence', orderEvidenceRoutes);
router.use('/orders', orderRoutes);
router.use('/deposits', depositRoutes);
router.use('/deposit-policy', depositPolicyRoutes);
router.use('/kyc', kycRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/users', userManagementRoutes);
router.use('/admin/orders', orderManagementRoutes);
router.post('/ai/chat', chatController);
export default router;
